export const pgErrorClass = {
  '00': 'Successful Completion',
  '01': 'Warning',
  '02': 'No Data (this is also a warning class per the SQL standard)',
  '03': 'SQL Statement Not Yet Complete',
  '08': 'Connection Exception',
  '09': 'Triggered Action Exception',
  '0A': 'Feature Not Supported',
  '0B': 'Invalid Transaction Initiation',
  '0F': 'Locator Exception',
  '0L': 'Invalid Grantor',
  '0P': 'Invalid Role Specification',
  '0Z': 'Diagnostics Exception',
  '20': 'Case Not Found',
  '21': 'Cardinality Violation',
  '22': 'Data Exception',
  '23': 'Integrity Constraint Violation',
  '24': 'Invalid Cursor State',
  '25': 'Invalid Transaction State',
  '26': 'Invalid SQL Statement Name',
  '27': 'Triggered Data Change Violation',
  '28': 'Invalid Authorization Specification',
  '2B': 'Dependent Privilege Descriptors Still Exist',
  '2D': 'Invalid Transaction Termination',
  '2F': 'SQL Routine Exception',
  '34': 'Invalid Cursor Name',
  '38': 'External Routine Exception',
  '39': 'External Routine Invocation Exception',
  '3B': 'Savepoint Exception',
  '3D': 'Invalid Catalog Name',
  '3F': 'Invalid Schema Name',
  '40': 'Transaction Rollback',
  '42': 'Syntax Error or Access Rule Violation',
  '44': 'WITH CHECK OPTION Violation',
  '53': 'Insufficient Resources',
  '54': 'Program Limit Exceeded',
  '55': 'Object Not In Prerequisite State',
  '57': 'Operator Intervention',
  '58': 'System Error (errors external to PostgreSQL itself)',
  '72': 'Snapshot Failure',
  'F0': 'Configuration File Error',
  'HV': 'Foreign Data Wrapper Error(SQL / MED)',
  'P0': 'PL / pgSQL Error',
  'XX': 'Internal Error',
};

export const pgError = {
  '00000': { errorClass: pgErrorClass['00'], conditionName: 'successful_completion', },
  '01000': { errorClass: pgErrorClass['01'], conditionName: 'warning', },
  '0100C': { errorClass: pgErrorClass['01'], conditionName: 'dynamic_result_sets_returned', },
  '01008': { errorClass: pgErrorClass['01'], conditionName: 'implicit_zero_bit_padding', },
  '01003': { errorClass: pgErrorClass['01'], conditionName: 'null_value_eliminated_in_set_function', },
  '01007': { errorClass: pgErrorClass['01'], conditionName: 'privilege_not_granted', },
  '01006': { errorClass: pgErrorClass['01'], conditionName: 'privilege_not_revoked', },
  '01004': { errorClass: pgErrorClass['01'], conditionName: 'string_data_right_truncation', },
  '01P01': { errorClass: pgErrorClass['01'], conditionName: 'deprecated_feature', },
  '02000': { errorClass: pgErrorClass['02'], conditionName: 'no_data', },
  '02001': { errorClass: pgErrorClass['02'], conditionName: 'no_additional_dynamic_result_sets_returned', },
  '03000': { errorClass: pgErrorClass['03'], conditionName: 'sql_statement_not_yet_complete', },
  '08000': { errorClass: pgErrorClass['08'], conditionName: 'connection_exception', },
  '08003': { errorClass: pgErrorClass['08'], conditionName: 'connection_does_not_exist', },
  '08006': { errorClass: pgErrorClass['08'], conditionName: 'connection_failure', },
  '08001': { errorClass: pgErrorClass['08'], conditionName: 'sqlclient_unable_to_establish_sqlconnection', },
  '08004': { errorClass: pgErrorClass['08'], conditionName: 'sqlserver_rejected_establishment_of_sqlconnection', },
  '08007': { errorClass: pgErrorClass['08'], conditionName: 'transaction_resolution_unknown', },
  '08P01': { errorClass: pgErrorClass['08'], conditionName: 'protocol_violation', },
  '09000': { errorClass: pgErrorClass['09'], conditionName: 'triggered_action_exception', },
  '0A000': { errorClass: pgErrorClass['0A'], conditionName: 'feature_not_supported', },
  '0B000': { errorClass: pgErrorClass['0B'], conditionName: 'invalid_transaction_initiation', },
  '0F000': { errorClass: pgErrorClass['0F'], conditionName: 'locator_exception', },
  '0F001': { errorClass: pgErrorClass['0F'], conditionName: 'invalid_locator_specification', },
  '0L000': { errorClass: pgErrorClass['0L'], conditionName: 'invalid_grantor', },
  '0LP01': { errorClass: pgErrorClass['0L'], conditionName: 'invalid_grant_operation', },
  '0P000': { errorClass: pgErrorClass['0P'], conditionName: 'invalid_role_specification', },
  '0Z000': { errorClass: pgErrorClass['0Z'], conditionName: 'diagnostics_exception', },
  '0Z002': { errorClass: pgErrorClass['0Z'], conditionName: 'stacked_diagnostics_accessed_without_active_handler', },
  '20000': { errorClass: pgErrorClass['20'], conditionName: 'case_not_found', },
  '21000': { errorClass: pgErrorClass['21'], conditionName: 'cardinality_violation', },
  '22000': { errorClass: pgErrorClass['22'], conditionName: 'data_exception', },
  '2202E': { errorClass: pgErrorClass['22'], conditionName: 'array_subscript_error', },
  '22021': { errorClass: pgErrorClass['22'], conditionName: 'character_not_in_repertoire', },
  '22008': { errorClass: pgErrorClass['22'], conditionName: 'datetime_field_overflow', },
  '22012': { errorClass: pgErrorClass['22'], conditionName: 'division_by_zero', },
  '22005': { errorClass: pgErrorClass['22'], conditionName: 'error_in_assignment', },
  '2200B': { errorClass: pgErrorClass['22'], conditionName: 'escape_character_conflict', },
  '22022': { errorClass: pgErrorClass['22'], conditionName: 'indicator_overflow', },
  '22015': { errorClass: pgErrorClass['22'], conditionName: 'interval_field_overflow', },
  '2201E': { errorClass: pgErrorClass['22'], conditionName: 'invalid_argument_for_logarithm', },
  '22014': { errorClass: pgErrorClass['22'], conditionName: 'invalid_argument_for_ntile_function', },
  '22016': { errorClass: pgErrorClass['22'], conditionName: 'invalid_argument_for_nth_value_function', },
  '2201F': { errorClass: pgErrorClass['22'], conditionName: 'invalid_argument_for_power_function', },
  '2201G': { errorClass: pgErrorClass['22'], conditionName: 'invalid_argument_for_width_bucket_function', },
  '22018': { errorClass: pgErrorClass['22'], conditionName: 'invalid_character_value_for_cast', },
  '22007': { errorClass: pgErrorClass['22'], conditionName: 'invalid_datetime_format', },
  '22019': { errorClass: pgErrorClass['22'], conditionName: 'invalid_escape_character', },
  '2200D': { errorClass: pgErrorClass['22'], conditionName: 'invalid_escape_octet', },
  '22025': { errorClass: pgErrorClass['22'], conditionName: 'invalid_escape_sequence', },
  '22P06': { errorClass: pgErrorClass['22'], conditionName: 'nonstandard_use_of_escape_character', },
  '22010': { errorClass: pgErrorClass['22'], conditionName: 'invalid_indicator_parameter_value', },
  '22023': { errorClass: pgErrorClass['22'], conditionName: 'invalid_parameter_value', },
  '2201B': { errorClass: pgErrorClass['22'], conditionName: 'invalid_regular_expression', },
  '2201W': { errorClass: pgErrorClass['22'], conditionName: 'invalid_row_count_in_limit_clause', },
  '2201X': { errorClass: pgErrorClass['22'], conditionName: 'invalid_row_count_in_result_offset_clause', },
  '2202H': { errorClass: pgErrorClass['22'], conditionName: 'invalid_tablesample_argument', },
  '2202G': { errorClass: pgErrorClass['22'], conditionName: 'invalid_tablesample_repeat', },
  '22009': { errorClass: pgErrorClass['22'], conditionName: 'invalid_time_zone_displacement_value', },
  '2200C': { errorClass: pgErrorClass['22'], conditionName: 'invalid_use_of_escape_character', },
  '2200G': { errorClass: pgErrorClass['22'], conditionName: 'most_specific_type_mismatch', },
  '22004': { errorClass: pgErrorClass['22'], conditionName: 'null_value_not_allowed', },
  '22002': { errorClass: pgErrorClass['22'], conditionName: 'null_value_no_indicator_parameter', },
  '22003': { errorClass: pgErrorClass['22'], conditionName: 'numeric_value_out_of_range', },
  '2200H': { errorClass: pgErrorClass['22'], conditionName: 'sequence_generator_limit_exceeded', },
  '22026': { errorClass: pgErrorClass['22'], conditionName: 'string_data_length_mismatch', },
  '22001': { errorClass: pgErrorClass['22'], conditionName: 'string_data_right_truncation', },
  '22011': { errorClass: pgErrorClass['22'], conditionName: 'substring_error', },
  '22027': { errorClass: pgErrorClass['22'], conditionName: 'trim_error', },
  '22024': { errorClass: pgErrorClass['22'], conditionName: 'unterminated_c_string', },
  '2200F': { errorClass: pgErrorClass['22'], conditionName: 'zero_length_character_string', },
  '22P01': { errorClass: pgErrorClass['22'], conditionName: 'floating_point_exception', },
  '22P02': { errorClass: pgErrorClass['22'], conditionName: 'invalid_text_representation', },
  '22P03': { errorClass: pgErrorClass['22'], conditionName: 'invalid_binary_representation', },
  '22P04': { errorClass: pgErrorClass['22'], conditionName: 'bad_copy_file_format', },
  '22P05': { errorClass: pgErrorClass['22'], conditionName: 'untranslatable_character', },
  '2200L': { errorClass: pgErrorClass['22'], conditionName: 'not_an_xml_document', },
  '2200M': { errorClass: pgErrorClass['22'], conditionName: 'invalid_xml_document', },
  '2200N': { errorClass: pgErrorClass['22'], conditionName: 'invalid_xml_content', },
  '2200S': { errorClass: pgErrorClass['22'], conditionName: 'invalid_xml_comment', },
  '2200T': { errorClass: pgErrorClass['22'], conditionName: 'invalid_xml_processing_instruction', },
  '23000': { errorClass: pgErrorClass['23'], conditionName: 'integrity_constraint_violation', },
  '23001': { errorClass: pgErrorClass['23'], conditionName: 'restrict_violation', },
  '23502': { errorClass: pgErrorClass['23'], conditionName: 'not_null_violation', },
  '23503': { errorClass: pgErrorClass['23'], conditionName: 'foreign_key_violation', },
  '23505': { errorClass: pgErrorClass['23'], conditionName: 'unique_violation', },
  '23514': { errorClass: pgErrorClass['23'], conditionName: 'check_violation', },
  '23P01': { errorClass: pgErrorClass['23'], conditionName: 'exclusion_violation', },
  '24000': { errorClass: pgErrorClass['24'], conditionName: 'invalid_cursor_state', },
  '25000': { errorClass: pgErrorClass['25'], conditionName: 'invalid_transaction_state', },
  '25001': { errorClass: pgErrorClass['25'], conditionName: 'active_sql_transaction', },
  '25002': { errorClass: pgErrorClass['25'], conditionName: 'branch_transaction_already_active', },
  '25008': { errorClass: pgErrorClass['25'], conditionName: 'held_cursor_requires_same_isolation_level', },
  '25003': { errorClass: pgErrorClass['25'], conditionName: 'inappropriate_access_mode_for_branch_transaction', },
  '25004': { errorClass: pgErrorClass['25'], conditionName: 'inappropriate_isolation_level_for_branch_transaction', },
  '25005': { errorClass: pgErrorClass['25'], conditionName: 'no_active_sql_transaction_for_branch_transaction', },
  '25006': { errorClass: pgErrorClass['25'], conditionName: 'read_only_sql_transaction', },
  '25007': { errorClass: pgErrorClass['25'], conditionName: 'schema_and_data_statement_mixing_not_supported', },
  '25P01': { errorClass: pgErrorClass['25'], conditionName: 'no_active_sql_transaction', },
  '25P02': { errorClass: pgErrorClass['25'], conditionName: 'in_failed_sql_transaction', },
  '25P03': { errorClass: pgErrorClass['25'], conditionName: 'idle_in_transaction_session_timeout', },
  '26000': { errorClass: pgErrorClass['26'], conditionName: 'invalid_sql_statement_name', },
  '27000': { errorClass: pgErrorClass['27'], conditionName: 'triggered_data_change_violation', },
  '28000': { errorClass: pgErrorClass['28'], conditionName: 'invalid_authorization_specification', },
  '28P01': { errorClass: pgErrorClass['28'], conditionName: 'invalid_password', },
  '2B000': { errorClass: pgErrorClass['2B'], conditionName: 'dependent_privilege_descriptors_still_exist', },
  '2BP01': { errorClass: pgErrorClass['2B'], conditionName: 'dependent_objects_still_exist', },
  '2D000': { errorClass: pgErrorClass['2D'], conditionName: 'invalid_transaction_termination', },
  '2F000': { errorClass: pgErrorClass['2F'], conditionName: 'sql_routine_exception', },
  '2F005': { errorClass: pgErrorClass['2F'], conditionName: 'function_executed_no_return_statement', },
  '2F002': { errorClass: pgErrorClass['2F'], conditionName: 'modifying_sql_data_not_permitted', },
  '2F003': { errorClass: pgErrorClass['2F'], conditionName: 'prohibited_sql_statement_attempted', },
  '2F004': { errorClass: pgErrorClass['2F'], conditionName: 'reading_sql_data_not_permitted', },
  '34000': { errorClass: pgErrorClass['34'], conditionName: 'invalid_cursor_name', },
  '38000': { errorClass: pgErrorClass['38'], conditionName: 'external_routine_exception', },
  '38001': { errorClass: pgErrorClass['38'], conditionName: 'containing_sql_not_permitted', },
  '38002': { errorClass: pgErrorClass['38'], conditionName: 'modifying_sql_data_not_permitted', },
  '38003': { errorClass: pgErrorClass['38'], conditionName: 'prohibited_sql_statement_attempted', },
  '38004': { errorClass: pgErrorClass['38'], conditionName: 'reading_sql_data_not_permitted', },
  '39000': { errorClass: pgErrorClass['39'], conditionName: 'external_routine_invocation_exception', },
  '39001': { errorClass: pgErrorClass['39'], conditionName: 'invalid_sqlstate_returned', },
  '39004': { errorClass: pgErrorClass['39'], conditionName: 'null_value_not_allowed', },
  '39P01': { errorClass: pgErrorClass['39'], conditionName: 'trigger_protocol_violated', },
  '39P02': { errorClass: pgErrorClass['39'], conditionName: 'srf_protocol_violated', },
  '39P03': { errorClass: pgErrorClass['39'], conditionName: 'event_trigger_protocol_violated', },
  '3B000': { errorClass: pgErrorClass['3B'], conditionName: 'savepoint_exception', },
  '3B001': { errorClass: pgErrorClass['3B'], conditionName: 'invalid_savepoint_specification', },
  '3D000': { errorClass: pgErrorClass['3D'], conditionName: 'invalid_catalog_name', },
  '3F000': { errorClass: pgErrorClass['3F'], conditionName: 'invalid_schema_name', },
  '40000': { errorClass: pgErrorClass['40'], conditionName: 'transaction_rollback', },
  '40002': { errorClass: pgErrorClass['40'], conditionName: 'transaction_integrity_constraint_violation', },
  '40001': { errorClass: pgErrorClass['40'], conditionName: 'serialization_failure', },
  '40003': { errorClass: pgErrorClass['40'], conditionName: 'statement_completion_unknown', },
  '40P01': { errorClass: pgErrorClass['40'], conditionName: 'deadlock_detected', },
  '42000': { errorClass: pgErrorClass['42'], conditionName: 'syntax_error_or_access_rule_violation', },
  '42601': { errorClass: pgErrorClass['42'], conditionName: 'syntax_error', },
  '42501': { errorClass: pgErrorClass['42'], conditionName: 'insufficient_privilege', },
  '42846': { errorClass: pgErrorClass['42'], conditionName: 'cannot_coerce', },
  '42803': { errorClass: pgErrorClass['42'], conditionName: 'grouping_error', },
  '42P20': { errorClass: pgErrorClass['42'], conditionName: 'windowing_error', },
  '42P19': { errorClass: pgErrorClass['42'], conditionName: 'invalid_recursion', },
  '42830': { errorClass: pgErrorClass['42'], conditionName: 'invalid_foreign_key', },
  '42602': { errorClass: pgErrorClass['42'], conditionName: 'invalid_name', },
  '42622': { errorClass: pgErrorClass['42'], conditionName: 'name_too_long', },
  '42939': { errorClass: pgErrorClass['42'], conditionName: 'reserved_name', },
  '42804': { errorClass: pgErrorClass['42'], conditionName: 'datatype_mismatch', },
  '42P18': { errorClass: pgErrorClass['42'], conditionName: 'indeterminate_datatype', },
  '42P21': { errorClass: pgErrorClass['42'], conditionName: 'collation_mismatch', },
  '42P22': { errorClass: pgErrorClass['42'], conditionName: 'indeterminate_collation', },
  '42809': { errorClass: pgErrorClass['42'], conditionName: 'wrong_object_type', },
  '428C9': { errorClass: pgErrorClass['42'], conditionName: 'generated_always', },
  '42703': { errorClass: pgErrorClass['42'], conditionName: 'undefined_column', },
  '42883': { errorClass: pgErrorClass['42'], conditionName: 'undefined_function', },
  '42P01': { errorClass: pgErrorClass['42'], conditionName: 'undefined_table', },
  '42P02': { errorClass: pgErrorClass['42'], conditionName: 'undefined_parameter', },
  '42704': { errorClass: pgErrorClass['42'], conditionName: 'undefined_object', },
  '42701': { errorClass: pgErrorClass['42'], conditionName: 'duplicate_column', },
  '42P03': { errorClass: pgErrorClass['42'], conditionName: 'duplicate_cursor', },
  '42P04': { errorClass: pgErrorClass['42'], conditionName: 'duplicate_database', },
  '42723': { errorClass: pgErrorClass['42'], conditionName: 'duplicate_function', },
  '42P05': { errorClass: pgErrorClass['42'], conditionName: 'duplicate_prepared_statement', },
  '42P06': { errorClass: pgErrorClass['42'], conditionName: 'duplicate_schema', },
  '42P07': { errorClass: pgErrorClass['42'], conditionName: 'duplicate_table', },
  '42712': { errorClass: pgErrorClass['42'], conditionName: 'duplicate_alias', },
  '42710': { errorClass: pgErrorClass['42'], conditionName: 'duplicate_object', },
  '42702': { errorClass: pgErrorClass['42'], conditionName: 'ambiguous_column', },
  '42725': { errorClass: pgErrorClass['42'], conditionName: 'ambiguous_function', },
  '42P08': { errorClass: pgErrorClass['42'], conditionName: 'ambiguous_parameter', },
  '42P09': { errorClass: pgErrorClass['42'], conditionName: 'ambiguous_alias', },
  '42P10': { errorClass: pgErrorClass['42'], conditionName: 'invalid_column_reference', },
  '42611': { errorClass: pgErrorClass['42'], conditionName: 'invalid_column_definition', },
  '42P11': { errorClass: pgErrorClass['42'], conditionName: 'invalid_cursor_definition', },
  '42P12': { errorClass: pgErrorClass['42'], conditionName: 'invalid_database_definition', },
  '42P13': { errorClass: pgErrorClass['42'], conditionName: 'invalid_function_definition', },
  '42P14': { errorClass: pgErrorClass['42'], conditionName: 'invalid_prepared_statement_definition', },
  '42P15': { errorClass: pgErrorClass['42'], conditionName: 'invalid_schema_definition', },
  '42P16': { errorClass: pgErrorClass['42'], conditionName: 'invalid_table_definition', },
  '42P17': { errorClass: pgErrorClass['42'], conditionName: 'invalid_object_definition', },
  '44000': { errorClass: pgErrorClass['44'], conditionName: 'with_check_option_violation', },
  '53000': { errorClass: pgErrorClass['53'], conditionName: 'insufficient_resources', },
  '53100': { errorClass: pgErrorClass['53'], conditionName: 'disk_full', },
  '53200': { errorClass: pgErrorClass['53'], conditionName: 'out_of_memory', },
  '53300': { errorClass: pgErrorClass['53'], conditionName: 'too_many_connections', },
  '53400': { errorClass: pgErrorClass['53'], conditionName: 'configuration_limit_exceeded', },
  '54000': { errorClass: pgErrorClass['54'], conditionName: 'program_limit_exceeded', },
  '54001': { errorClass: pgErrorClass['54'], conditionName: 'statement_too_complex', },
  '54011': { errorClass: pgErrorClass['54'], conditionName: 'too_many_columns', },
  '54023': { errorClass: pgErrorClass['54'], conditionName: 'too_many_arguments', },
  '55000': { errorClass: pgErrorClass['55'], conditionName: 'object_not_in_prerequisite_state', },
  '55006': { errorClass: pgErrorClass['55'], conditionName: 'object_in_use', },
  '55P02': { errorClass: pgErrorClass['55'], conditionName: 'cant_change_runtime_param', },
  '55P03': { errorClass: pgErrorClass['55'], conditionName: 'lock_not_available', },
  '57000': { errorClass: pgErrorClass['57'], conditionName: 'operator_intervention', },
  '57014': { errorClass: pgErrorClass['57'], conditionName: 'query_canceled', },
  '57P01': { errorClass: pgErrorClass['57'], conditionName: 'admin_shutdown', },
  '57P02': { errorClass: pgErrorClass['57'], conditionName: 'crash_shutdown', },
  '57P03': { errorClass: pgErrorClass['57'], conditionName: 'cannot_connect_now', },
  '57P04': { errorClass: pgErrorClass['57'], conditionName: 'database_dropped', },
  '58000': { errorClass: pgErrorClass['58'], conditionName: 'system_error', },
  '58030': { errorClass: pgErrorClass['58'], conditionName: 'io_error', },
  '58P01': { errorClass: pgErrorClass['58'], conditionName: 'undefined_file', },
  '58P02': { errorClass: pgErrorClass['58'], conditionName: 'duplicate_file', },
  '72000': { errorClass: pgErrorClass['72'], conditionName: 'snapshot_too_old', },
  'F0000': { errorClass: pgErrorClass['F0'], conditionName: 'config_file_error', },
  'F0001': { errorClass: pgErrorClass['F0'], conditionName: 'lock_file_exists', },
  'HV000': { errorClass: pgErrorClass['HV'], conditionName: 'fdw_error', },
  'HV005': { errorClass: pgErrorClass['HV'], conditionName: 'fdw_column_name_not_found', },
  'HV002': { errorClass: pgErrorClass['HV'], conditionName: 'fdw_dynamic_parameter_value_needed', },
  'HV010': { errorClass: pgErrorClass['HV'], conditionName: 'fdw_function_sequence_error', },
  'HV021': { errorClass: pgErrorClass['HV'], conditionName: 'fdw_inconsistent_descriptor_information', },
  'HV024': { errorClass: pgErrorClass['HV'], conditionName: 'fdw_invalid_attribute_value', },
  'HV007': { errorClass: pgErrorClass['HV'], conditionName: 'fdw_invalid_column_name', },
  'HV008': { errorClass: pgErrorClass['HV'], conditionName: 'fdw_invalid_column_number', },
  'HV004': { errorClass: pgErrorClass['HV'], conditionName: 'fdw_invalid_data_type', },
  'HV006': { errorClass: pgErrorClass['HV'], conditionName: 'fdw_invalid_data_type_descriptors', },
  'HV091': { errorClass: pgErrorClass['HV'], conditionName: 'fdw_invalid_descriptor_field_identifier', },
  'HV00B': { errorClass: pgErrorClass['HV'], conditionName: 'fdw_invalid_handle', },
  'HV00C': { errorClass: pgErrorClass['HV'], conditionName: 'fdw_invalid_option_index', },
  'HV00D': { errorClass: pgErrorClass['HV'], conditionName: 'fdw_invalid_option_name', },
  'HV090': { errorClass: pgErrorClass['HV'], conditionName: 'fdw_invalid_string_length_or_buffer_length', },
  'HV00A': { errorClass: pgErrorClass['HV'], conditionName: 'fdw_invalid_string_format', },
  'HV009': { errorClass: pgErrorClass['HV'], conditionName: 'fdw_invalid_use_of_null_pointer', },
  'HV014': { errorClass: pgErrorClass['HV'], conditionName: 'fdw_too_many_handles', },
  'HV001': { errorClass: pgErrorClass['HV'], conditionName: 'fdw_out_of_memory', },
  'HV00P': { errorClass: pgErrorClass['HV'], conditionName: 'fdw_no_schemas', },
  'HV00J': { errorClass: pgErrorClass['HV'], conditionName: 'fdw_option_name_not_found', },
  'HV00K': { errorClass: pgErrorClass['HV'], conditionName: 'fdw_reply_handle', },
  'HV00Q': { errorClass: pgErrorClass['HV'], conditionName: 'fdw_schema_not_found', },
  'HV00R': { errorClass: pgErrorClass['HV'], conditionName: 'fdw_table_not_found', },
  'HV00L': { errorClass: pgErrorClass['HV'], conditionName: 'fdw_unable_to_create_execution', },
  'HV00M': { errorClass: pgErrorClass['HV'], conditionName: 'fdw_unable_to_create_reply', },
  'HV00N': { errorClass: pgErrorClass['HV'], conditionName: 'fdw_unable_to_establish_connection', },
  'P0000': { errorClass: pgErrorClass['P0'], conditionName: 'plpgsql_error', },
  'P0001': { errorClass: pgErrorClass['P0'], conditionName: 'raise_exception', },
  'P0002': { errorClass: pgErrorClass['P0'], conditionName: 'no_data_found', },
  'P0003': { errorClass: pgErrorClass['P0'], conditionName: 'too_many_rows', },
  'P0004': { errorClass: pgErrorClass['P0'], conditionName: 'assert_failure', },
  'XX000': { errorClass: pgErrorClass['XX'], conditionName: 'internal_error', },
  'XX001': { errorClass: pgErrorClass['XX'], conditionName: 'data_corrupted', },
  'XX002': { errorClass: pgErrorClass['XX'], conditionName: 'index_corrupted', },
};

export default function getErrorDescription(code) {
  const fullDescription = pgError[code];
  if (fullDescription) return fullDescription;

  const errorClassCode = code.substring(0,2);

  return {
    errorClass: pgErrorClass[errorClassCode] || `Unknown class ${errorClassCode}`,
    conditionName: `Unknown code ${code}`,
  }
}